server:
  port: 8762

spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true 